### ISSUE TITLE
我想用这个开源代码

### ISSUE THREAD

**Issue by IOCloudFly** [madeeldev/flutter-vpn#1]
方便的话，我可以给你$。请问有没有mac/win UI Image

**Comment by madeeldev** [comment]
> 方便的话，我可以给你$。请问有没有mac/win UI Image

Thank you for reaching out and showing interest in the VPN project. I'm glad to hear that you find it useful!

Regarding your question about the Mac/Windows UI image, currently, the project focuses on Flutter, which allows for cross-platform development of mobile apps for iOS and Android. As such, there isn't a specific Mac or Windows UI image included in the repository.

However, you can easily customize the UI to match the design principles and guidelines of Mac or Windows platforms by adapting the UI components provided in the project. If you have specific design requirements or need assistance with customization, feel free to provide more details, and I'll do my best to help.
